// 20210319172236
// https://yts.mx/api/v2/list_movies.json?sort_by=rating

{
    "status": "ok",
    "status_message": "Query was successful",
    "data": {
      "movie_count": 28522,
      "limit": 20,
      "page_number": 1,
      "movies": [
        {
          "id": 25171,
          "url": "https://yts.mx/movies/erasing-family-2020",
          "imdb_code": "tt9252316",
          "title": "Erasing Family",
          "title_english": "Erasing Family",
          "title_long": "Erasing Family (2020)",
          "slug": "erasing-family-2020",
          "year": 2020,
          "rating": 9.5,
          "runtime": 0,
          "genres": [
            "Action",
            "Documentary"
          ],
          "summary": "In North America, over 25 MILLION PARENTS are being erased from their children's lives after divorce and separation. The ERASING FAMILY documentary follows young adults fighting to reunite with their broken families. Through the eyes of 23-year-old Ashlynn, 12-year-old Lauren and 28-year-old Brian, consequences on mental health caused by profiteering high-conflict divorce court settlements are revealed. The film shows programs that encourage mediation and shared parenting which will prevent parental alienation and future childhood trauma, making divorce and separation less costly both financially and emotionally. The film ends with children and parents being reunited on screen and will inspire other kids to reach out to #erased parents, siblings and grandparents.",
          "description_full": "In North America, over 25 MILLION PARENTS are being erased from their children's lives after divorce and separation. The ERASING FAMILY documentary follows young adults fighting to reunite with their broken families. Through the eyes of 23-year-old Ashlynn, 12-year-old Lauren and 28-year-old Brian, consequences on mental health caused by profiteering high-conflict divorce court settlements are revealed. The film shows programs that encourage mediation and shared parenting which will prevent parental alienation and future childhood trauma, making divorce and separation less costly both financially and emotionally. The film ends with children and parents being reunited on screen and will inspire other kids to reach out to #erased parents, siblings and grandparents.",
          "synopsis": "In North America, over 25 MILLION PARENTS are being erased from their children's lives after divorce and separation. The ERASING FAMILY documentary follows young adults fighting to reunite with their broken families. Through the eyes of 23-year-old Ashlynn, 12-year-old Lauren and 28-year-old Brian, consequences on mental health caused by profiteering high-conflict divorce court settlements are revealed. The film shows programs that encourage mediation and shared parenting which will prevent parental alienation and future childhood trauma, making divorce and separation less costly both financially and emotionally. The film ends with children and parents being reunited on screen and will inspire other kids to reach out to #erased parents, siblings and grandparents.",
          "yt_trailer_code": "",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/erasing_family_2020/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/erasing_family_2020/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/erasing_family_2020/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/erasing_family_2020/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/erasing_family_2020/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/08E1058482D1D357DC415711FD0486DAB645FE73",
              "hash": "08E1058482D1D357DC415711FD0486DAB645FE73",
              "quality": "720p",
              "type": "web",
              "seeds": 6,
              "peers": 2,
              "size": "851.11 MB",
              "size_bytes": 892453519,
              "date_uploaded": "2020-12-22 10:12:19",
              "date_uploaded_unix": 1608628339
            },
            {
              "url": "https://yts.mx/torrent/download/4F24FB5ABB9AA7764A02B74A3F83CBC0D0D313F4",
              "hash": "4F24FB5ABB9AA7764A02B74A3F83CBC0D0D313F4",
              "quality": "1080p",
              "type": "web",
              "seeds": 12,
              "peers": 2,
              "size": "1.54 GB",
              "size_bytes": 1653562409,
              "date_uploaded": "2020-12-22 12:07:26",
              "date_uploaded_unix": 1608635246
            }
          ],
          "date_uploaded": "2020-12-22 10:12:19",
          "date_uploaded_unix": 1608628339
        },
        {
          "id": 15553,
          "url": "https://yts.mx/movies/doctor-who-the-day-of-the-doctor-2013",
          "imdb_code": "tt2779318",
          "title": "Doctor Who The Day of the Doctor",
          "title_english": "Doctor Who The Day of the Doctor",
          "title_long": "Doctor Who The Day of the Doctor (2013)",
          "slug": "doctor-who-the-day-of-the-doctor-2013",
          "year": 2013,
          "rating": 9.4,
          "runtime": 77,
          "genres": [
            "Action",
            "Adventure",
            "Drama",
            "Family",
            "Mystery",
            "Sci-Fi"
          ],
          "summary": "In 2013, something terrible is awakening in London's National Gallery; in 1562, a murderous plot is afoot in Elizabethan England; and somewhere in space an ancient battle reaches its devastating conclusion.",
          "description_full": "In 2013, something terrible is awakening in London's National Gallery; in 1562, a murderous plot is afoot in Elizabethan England; and somewhere in space an ancient battle reaches its devastating conclusion.",
          "synopsis": "In 2013, something terrible is awakening in London's National Gallery; in 1562, a murderous plot is afoot in Elizabethan England; and somewhere in space an ancient battle reaches its devastating conclusion.",
          "yt_trailer_code": "Mkq8pnvsnQg",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/doctor_who_the_day_of_the_doctor_2013/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/doctor_who_the_day_of_the_doctor_2013/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/doctor_who_the_day_of_the_doctor_2013/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/doctor_who_the_day_of_the_doctor_2013/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/doctor_who_the_day_of_the_doctor_2013/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/522D19B70EB06419D339E4B1470640090CA69286",
              "hash": "522D19B70EB06419D339E4B1470640090CA69286",
              "quality": "720p",
              "type": "bluray",
              "seeds": 68,
              "peers": 3,
              "size": "734.9 MB",
              "size_bytes": 770598502,
              "date_uploaded": "2020-02-24 05:16:24",
              "date_uploaded_unix": 1582517784
            },
            {
              "url": "https://yts.mx/torrent/download/682E309437DFAE8BA08F44AD00D236B94FC0CD30",
              "hash": "682E309437DFAE8BA08F44AD00D236B94FC0CD30",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 88,
              "peers": 2,
              "size": "1.42 GB",
              "size_bytes": 1524713390,
              "date_uploaded": "2020-02-24 07:15:16",
              "date_uploaded_unix": 1582524916
            }
          ],
          "date_uploaded": "2020-02-24 05:16:24",
          "date_uploaded_unix": 1582517784
        },
        {
          "id": 3709,
          "url": "https://yts.mx/movies/the-shawshank-redemption-1994",
          "imdb_code": "tt0111161",
          "title": "The Shawshank Redemption",
          "title_english": "The Shawshank Redemption",
          "title_long": "The Shawshank Redemption (1994)",
          "slug": "the-shawshank-redemption-1994",
          "year": 1994,
          "rating": 9.3,
          "runtime": 142,
          "genres": [
            "Action",
            "Crime",
            "Drama"
          ],
          "summary": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
          "description_full": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
          "synopsis": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
          "yt_trailer_code": "9qqfMvKxBa0",
          "language": "en",
          "mpa_rating": "R",
          "background_image": "https://yts.mx/assets/images/movies/The_Shawshank_Redemption_1994/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/The_Shawshank_Redemption_1994/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/The_Shawshank_Redemption_1994/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/The_Shawshank_Redemption_1994/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/The_Shawshank_Redemption_1994/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE",
              "hash": "AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE",
              "quality": "720p",
              "type": "bluray",
              "seeds": 76,
              "peers": 35,
              "size": "848.96 MB",
              "size_bytes": 890199081,
              "date_uploaded": "2015-11-01 03:20:23",
              "date_uploaded_unix": 1446344423
            },
            {
              "url": "https://yts.mx/torrent/download/E0D00667650ABA9EE05AACBBBD8B55EA8A51F534",
              "hash": "E0D00667650ABA9EE05AACBBBD8B55EA8A51F534",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 150,
              "peers": 14,
              "size": "1.60 GB",
              "size_bytes": 1717986918,
              "date_uploaded": "2015-11-01 03:20:25",
              "date_uploaded_unix": 1446344425
            }
          ],
          "date_uploaded": "2015-11-01 03:20:23",
          "date_uploaded_unix": 1446344423
        },
        {
          "id": 3304,
          "url": "https://yts.mx/movies/the-godfather-1972",
          "imdb_code": "tt0068646",
          "title": "The Godfather",
          "title_english": "The Godfather",
          "title_long": "The Godfather (1972)",
          "slug": "the-godfather-1972",
          "year": 1972,
          "rating": 9.2,
          "runtime": 175,
          "genres": [
            "Action",
            "Crime",
            "Drama"
          ],
          "summary": "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
          "description_full": "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
          "synopsis": "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
          "yt_trailer_code": "fBNpSRtfIUA",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/The_Godfather_1972/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/The_Godfather_1972/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/The_Godfather_1972/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/The_Godfather_1972/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/The_Godfather_1972/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/C168B84FC2B8CF062B67E4168E35C98F10BC7C74",
              "hash": "C168B84FC2B8CF062B67E4168E35C98F10BC7C74",
              "quality": "720p",
              "type": "bluray",
              "seeds": 56,
              "peers": 38,
              "size": "1.20 GB",
              "size_bytes": 1288490189,
              "date_uploaded": "2015-11-01 02:36:37",
              "date_uploaded_unix": 1446341797
            },
            {
              "url": "https://yts.mx/torrent/download/5E915039C619366E490D08DB3FFED21F3A3AE84A",
              "hash": "5E915039C619366E490D08DB3FFED21F3A3AE84A",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 289,
              "peers": 89,
              "size": "2.40 GB",
              "size_bytes": 2576980378,
              "date_uploaded": "2015-11-01 02:36:38",
              "date_uploaded_unix": 1446341798
            },
            {
              "url": "https://yts.mx/torrent/download/EAEFB74B7736D4579CC3DA91457DA7A755BABC3A",
              "hash": "EAEFB74B7736D4579CC3DA91457DA7A755BABC3A",
              "quality": "2160p",
              "type": "web",
              "seeds": 54,
              "peers": 15,
              "size": "7.9 GB",
              "size_bytes": 8482560410,
              "date_uploaded": "2020-09-05 14:58:40",
              "date_uploaded_unix": 1599310720
            }
          ],
          "date_uploaded": "2015-11-01 02:36:37",
          "date_uploaded_unix": 1446341797
        },
        {
          "id": 15527,
          "url": "https://yts.mx/movies/top-gear-africa-special-part-1-2013",
          "imdb_code": "tt2741136",
          "title": "Top Gear Africa Special, Part 1",
          "title_english": "Top Gear Africa Special, Part 1",
          "title_long": "Top Gear Africa Special, Part 1 (2013)",
          "slug": "top-gear-africa-special-part-1-2013",
          "year": 2013,
          "rating": 9.2,
          "runtime": 59,
          "genres": [
            "Action",
            "Adventure",
            "Comedy",
            "Reality-TV",
            "Talk-Show"
          ],
          "summary": "In the first of a two-part Top Gear special, Jeremy Clarkson, Richard Hammond and James May are in Africa with a simple mission - to find the definitive source of the Nile. Over the years many explorers claim to have already done just that, but the Top Gear trio believe that they can do better by traveling using only grit, ingenuity and three ageing estate cars.",
          "description_full": "In the first of a two-part Top Gear special, Jeremy Clarkson, Richard Hammond and James May are in Africa with a simple mission - to find the definitive source of the Nile. Over the years many explorers claim to have already done just that, but the Top Gear trio believe that they can do better by traveling using only grit, ingenuity and three ageing estate cars.",
          "synopsis": "In the first of a two-part Top Gear special, Jeremy Clarkson, Richard Hammond and James May are in Africa with a simple mission - to find the definitive source of the Nile. Over the years many explorers claim to have already done just that, but the Top Gear trio believe that they can do better by traveling using only grit, ingenuity and three ageing estate cars.",
          "yt_trailer_code": "",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/top_gear_africa_special_part_1_2013/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/top_gear_africa_special_part_1_2013/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/top_gear_africa_special_part_1_2013/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/top_gear_africa_special_part_1_2013/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/top_gear_africa_special_part_1_2013/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/D76F89A72BF04B770A4B3C79EDBBCCBC8FEFDC70",
              "hash": "D76F89A72BF04B770A4B3C79EDBBCCBC8FEFDC70",
              "quality": "720p",
              "type": "web",
              "seeds": 18,
              "peers": 2,
              "size": "1.02 GB",
              "size_bytes": 1095216660,
              "date_uploaded": "2020-02-23 01:25:37",
              "date_uploaded_unix": 1582417537
            },
            {
              "url": "https://yts.mx/torrent/download/ECA37497C70EC2F4D2B81DCE0D297DC01CAD5236",
              "hash": "ECA37497C70EC2F4D2B81DCE0D297DC01CAD5236",
              "quality": "1080p",
              "type": "web",
              "seeds": 31,
              "peers": 3,
              "size": "1.89 GB",
              "size_bytes": 2029372047,
              "date_uploaded": "2020-02-23 03:25:48",
              "date_uploaded_unix": 1582424748
            }
          ],
          "date_uploaded": "2020-02-23 01:25:37",
          "date_uploaded_unix": 1582417537
        },
        {
          "id": 28936,
          "url": "https://yts.mx/movies/the-book-of-job-2019",
          "imdb_code": "tt11367408",
          "title": "The Book of Job",
          "title_english": "The Book of Job",
          "title_long": "The Book of Job (2019)",
          "slug": "the-book-of-job-2019",
          "year": 2019,
          "rating": 9.2,
          "runtime": 90,
          "genres": [
            "Comedy",
            "Drama"
          ],
          "summary": "The Book of Job is about a high school student who has trouble separating reality from fiction. Young Job falls \"madly in love\" with a new girl who catches his eye one Sunday mass. In the midst of his conforming to what he believes to be her idealized standards, he realizes his life is about so much more than simply himself.",
          "description_full": "The Book of Job is about a high school student who has trouble separating reality from fiction. Young Job falls \"madly in love\" with a new girl who catches his eye one Sunday mass. In the midst of his conforming to what he believes to be her idealized standards, he realizes his life is about so much more than simply himself.",
          "synopsis": "The Book of Job is about a high school student who has trouble separating reality from fiction. Young Job falls \"madly in love\" with a new girl who catches his eye one Sunday mass. In the midst of his conforming to what he believes to be her idealized standards, he realizes his life is about so much more than simply himself.",
          "yt_trailer_code": "",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/the_book_of_job_2019/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/the_book_of_job_2019/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/the_book_of_job_2019/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/the_book_of_job_2019/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/the_book_of_job_2019/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/0FCC75CD54F2B097432C0225BDD65CA375F34B91",
              "hash": "0FCC75CD54F2B097432C0225BDD65CA375F34B91",
              "quality": "720p",
              "type": "web",
              "seeds": 33,
              "peers": 13,
              "size": "831.55 MB",
              "size_bytes": 871943373,
              "date_uploaded": "2021-03-16 10:09:42",
              "date_uploaded_unix": 1615885782
            },
            {
              "url": "https://yts.mx/torrent/download/7E822A68091F5DA57F8B0C656BC98B1F845F3DDF",
              "hash": "7E822A68091F5DA57F8B0C656BC98B1F845F3DDF",
              "quality": "1080p",
              "type": "web",
              "seeds": 42,
              "peers": 17,
              "size": "1.67 GB",
              "size_bytes": 1793148846,
              "date_uploaded": "2021-03-16 11:08:14",
              "date_uploaded_unix": 1615889294
            }
          ],
          "date_uploaded": "2021-03-16 10:09:42",
          "date_uploaded_unix": 1615885782
        },
        {
          "id": 22032,
          "url": "https://yts.mx/movies/holbrooktwain-an-american-odyssey-2014",
          "imdb_code": "tt1745718",
          "title": "Holbrook/Twain: An American Odyssey",
          "title_english": "Holbrook/Twain: An American Odyssey",
          "title_long": "Holbrook/Twain: An American Odyssey (2014)",
          "slug": "holbrooktwain-an-american-odyssey-2014",
          "year": 2014,
          "rating": 9.1,
          "runtime": 93,
          "genres": [
            "Action",
            "Documentary"
          ],
          "summary": "HOLBROOK/TWAIN: AN AMERICAN ODYSSEY chronicles the triumphant and tumultuous history of the longest-running one-man show in the history of theatre, Hal Holbrook's Tony and Emmy Award-winning masterpiece, \"Mark Twain Tonight!\"",
          "description_full": "HOLBROOK/TWAIN: AN AMERICAN ODYSSEY chronicles the triumphant and tumultuous history of the longest-running one-man show in the history of theatre, Hal Holbrook's Tony and Emmy Award-winning masterpiece, \"Mark Twain Tonight!\"",
          "synopsis": "HOLBROOK/TWAIN: AN AMERICAN ODYSSEY chronicles the triumphant and tumultuous history of the longest-running one-man show in the history of theatre, Hal Holbrook's Tony and Emmy Award-winning masterpiece, \"Mark Twain Tonight!\"",
          "yt_trailer_code": "",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/holbrooktwain_an_american_odyssey_2014/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/holbrooktwain_an_american_odyssey_2014/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/holbrooktwain_an_american_odyssey_2014/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/holbrooktwain_an_american_odyssey_2014/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/holbrooktwain_an_american_odyssey_2014/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/20A061A242D1CF1F21DE67A67830724146A1FD5C",
              "hash": "20A061A242D1CF1F21DE67A67830724146A1FD5C",
              "quality": "720p",
              "type": "web",
              "seeds": 2,
              "peers": 1,
              "size": "855.4 MB",
              "size_bytes": 896951910,
              "date_uploaded": "2020-10-10 23:27:19",
              "date_uploaded_unix": 1602365239
            },
            {
              "url": "https://yts.mx/torrent/download/8DCDEC4FD107EF381C0D052844BE9405F1A04343",
              "hash": "8DCDEC4FD107EF381C0D052844BE9405F1A04343",
              "quality": "1080p",
              "type": "web",
              "seeds": 4,
              "peers": 2,
              "size": "1.72 GB",
              "size_bytes": 1846835937,
              "date_uploaded": "2020-10-11 01:22:10",
              "date_uploaded_unix": 1602372130
            }
          ],
          "date_uploaded": "2020-10-10 23:27:19",
          "date_uploaded_unix": 1602365239
        },
        {
          "id": 3175,
          "url": "https://yts.mx/movies/the-dark-knight-2008",
          "imdb_code": "tt0468569",
          "title": "The Dark Knight",
          "title_english": "The Dark Knight",
          "title_long": "The Dark Knight (2008)",
          "slug": "the-dark-knight-2008",
          "year": 2008,
          "rating": 9,
          "runtime": 152,
          "genres": [
            "Action",
            "Adventure",
            "Crime",
            "Drama",
            "Thriller"
          ],
          "summary": "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.",
          "description_full": "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.",
          "synopsis": "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.",
          "yt_trailer_code": "kmJLuwP3MbY",
          "language": "en",
          "mpa_rating": "PG-13",
          "background_image": "https://yts.mx/assets/images/movies/The_Dark_Knight_2008/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/The_Dark_Knight_2008/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/The_Dark_Knight_2008/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/The_Dark_Knight_2008/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/The_Dark_Knight_2008/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/F5D61BF3D57082BA2EE1305DA5DF8DCD10D34539",
              "hash": "F5D61BF3D57082BA2EE1305DA5DF8DCD10D34539",
              "quality": "720p",
              "type": "bluray",
              "seeds": 28,
              "peers": 17,
              "size": "949.99 MB",
              "size_bytes": 996136714,
              "date_uploaded": "2015-11-01 02:20:06",
              "date_uploaded_unix": 1446340806
            },
            {
              "url": "https://yts.mx/torrent/download/A54926C2E07B0E5F0243954330B599B31C804F0B",
              "hash": "A54926C2E07B0E5F0243954330B599B31C804F0B",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 215,
              "peers": 32,
              "size": "1.70 GB",
              "size_bytes": 1825361101,
              "date_uploaded": "2015-11-01 02:20:12",
              "date_uploaded_unix": 1446340812
            },
            {
              "url": "https://yts.mx/torrent/download/61BE42FB337B1B84F844B88FD904982A0A2330E3",
              "hash": "61BE42FB337B1B84F844B88FD904982A0A2330E3",
              "quality": "2160p",
              "type": "bluray",
              "seeds": 150,
              "peers": 25,
              "size": "7.52 GB",
              "size_bytes": 8074538516,
              "date_uploaded": "2020-05-26 17:14:13",
              "date_uploaded_unix": 1590506053
            }
          ],
          "date_uploaded": "2015-11-01 02:20:06",
          "date_uploaded_unix": 1446340806
        },
        {
          "id": 3305,
          "url": "https://yts.mx/movies/the-godfather-part-ii-1974",
          "imdb_code": "tt0071562",
          "title": "The Godfather: Part II",
          "title_english": "The Godfather: Part II",
          "title_long": "The Godfather: Part II (1974)",
          "slug": "the-godfather-part-ii-1974",
          "year": 1974,
          "rating": 9,
          "runtime": 202,
          "genres": [
            "Action",
            "Crime",
            "Drama"
          ],
          "summary": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
          "description_full": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
          "synopsis": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
          "yt_trailer_code": "9O1Iy9od7-A",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/The_Godfather_Part_II_1974/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/The_Godfather_Part_II_1974/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/The_Godfather_Part_II_1974/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/The_Godfather_Part_II_1974/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/The_Godfather_Part_II_1974/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/B27022D09BC067D46BBDB65AE62348AB3F21C727",
              "hash": "B27022D09BC067D46BBDB65AE62348AB3F21C727",
              "quality": "720p",
              "type": "bluray",
              "seeds": 96,
              "peers": 26,
              "size": "1.30 GB",
              "size_bytes": 1395864371,
              "date_uploaded": "2015-11-01 02:36:45",
              "date_uploaded_unix": 1446341805
            },
            {
              "url": "https://yts.mx/torrent/download/6C9124FE9A99B2001FAD76A76152691BC515A80D",
              "hash": "6C9124FE9A99B2001FAD76A76152691BC515A80D",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 31,
              "peers": 6,
              "size": "2.70 GB",
              "size_bytes": 2899102925,
              "date_uploaded": "2015-11-01 02:36:50",
              "date_uploaded_unix": 1446341810
            },
            {
              "url": "https://yts.mx/torrent/download/BAB595F912C144CEA3B001390384865B79F78D7C",
              "hash": "BAB595F912C144CEA3B001390384865B79F78D7C",
              "quality": "2160p",
              "type": "web",
              "seeds": 43,
              "peers": 9,
              "size": "9.01 GB",
              "size_bytes": 9674413834,
              "date_uploaded": "2020-09-06 08:21:12",
              "date_uploaded_unix": 1599373272
            }
          ],
          "date_uploaded": "2015-11-01 02:36:45",
          "date_uploaded_unix": 1446341805
        },
        {
          "id": 4253,
          "url": "https://yts.mx/movies/12-angry-men-1957",
          "imdb_code": "tt0050083",
          "title": "12 Angry Men",
          "title_english": "12 Angry Men",
          "title_long": "12 Angry Men (1957)",
          "slug": "12-angry-men-1957",
          "year": 1957,
          "rating": 9,
          "runtime": 96,
          "genres": [
            "Action",
            "Crime",
            "Drama"
          ],
          "summary": "The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room.",
          "description_full": "The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room.",
          "synopsis": "The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room.",
          "yt_trailer_code": "OvebOqneLIU",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/12_Angry_Men_1957/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/12_Angry_Men_1957/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/12_Angry_Men_1957/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/12_Angry_Men_1957/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/12_Angry_Men_1957/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/A303CAA20F46AAB9BBE75DA62B90E375FA03578A",
              "hash": "A303CAA20F46AAB9BBE75DA62B90E375FA03578A",
              "quality": "720p",
              "type": "bluray",
              "seeds": 72,
              "peers": 11,
              "size": "700.07 MB",
              "size_bytes": 734076600,
              "date_uploaded": "2015-10-31 20:46:02",
              "date_uploaded_unix": 1446320762
            },
            {
              "url": "https://yts.mx/torrent/download/4DB3FDD949B99781E6AB1979BA476EC3E932970C",
              "hash": "4DB3FDD949B99781E6AB1979BA476EC3E932970C",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 221,
              "peers": 33,
              "size": "1.52 GB",
              "size_bytes": 1632087572,
              "date_uploaded": "2018-04-28 02:11:22",
              "date_uploaded_unix": 1524874282
            }
          ],
          "date_uploaded": "2015-10-31 20:46:02",
          "date_uploaded_unix": 1446320762
        },
        {
          "id": 9717,
          "url": "https://yts.mx/movies/natsamrat-2016",
          "imdb_code": "tt5311546",
          "title": "Natsamrat",
          "title_english": "Natsamrat",
          "title_long": "Natsamrat (2016)",
          "slug": "natsamrat-2016",
          "year": 2016,
          "rating": 9,
          "runtime": 0,
          "genres": [
            "Action",
            "Drama",
            "Family"
          ],
          "summary": "The film is a tragedy about a veteran theatre actor named Ganpat \"Appa\" Belwalkar (Nana Patekar) who has been the best of his lot during his heyday, garnering fame and fortune acting in plays based on various works, especially William Shakespeare's. It is a tragedy of a veteran actor who enjoyed a very vital importance in his life but who becomes the victim of old age alienation and estrangement. The film reveals an intensely tragic fate of an actor who becomes victim of fate and fortune in old age, which is similar to the fate of Lear. Natsamrat suffers the pangs of old age and dishonor inflicted on him by his own children. It is a tragedy of great humanist and actor who succumbs to the ill fate and destiny. In fact, Natsamrat is a story of Ganpatrao Belvalkar, who withstands great suffering after his retirement from stage acting.",
          "description_full": "The film is a tragedy about a veteran theatre actor named Ganpat \"Appa\" Belwalkar (Nana Patekar) who has been the best of his lot during his heyday, garnering fame and fortune acting in plays based on various works, especially William Shakespeare's. It is a tragedy of a veteran actor who enjoyed a very vital importance in his life but who becomes the victim of old age alienation and estrangement. The film reveals an intensely tragic fate of an actor who becomes victim of fate and fortune in old age, which is similar to the fate of Lear. Natsamrat suffers the pangs of old age and dishonor inflicted on him by his own children. It is a tragedy of great humanist and actor who succumbs to the ill fate and destiny. In fact, Natsamrat is a story of Ganpatrao Belvalkar, who withstands great suffering after his retirement from stage acting.",
          "synopsis": "The film is a tragedy about a veteran theatre actor named Ganpat \"Appa\" Belwalkar (Nana Patekar) who has been the best of his lot during his heyday, garnering fame and fortune acting in plays based on various works, especially William Shakespeare's. It is a tragedy of a veteran actor who enjoyed a very vital importance in his life but who becomes the victim of old age alienation and estrangement. The film reveals an intensely tragic fate of an actor who becomes victim of fate and fortune in old age, which is similar to the fate of Lear. Natsamrat suffers the pangs of old age and dishonor inflicted on him by his own children. It is a tragedy of great humanist and actor who succumbs to the ill fate and destiny. In fact, Natsamrat is a story of Ganpatrao Belvalkar, who withstands great suffering after his retirement from stage acting.",
          "yt_trailer_code": "DCXDyIsPEN8",
          "language": "mr",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/natsamrat_2016/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/natsamrat_2016/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/natsamrat_2016/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/natsamrat_2016/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/natsamrat_2016/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/9C2440F9D38F769B768660FE715D36572776F681",
              "hash": "9C2440F9D38F769B768660FE715D36572776F681",
              "quality": "720p",
              "type": "web",
              "seeds": 13,
              "peers": 3,
              "size": "1.37 GB",
              "size_bytes": 1471026299,
              "date_uploaded": "2018-11-12 08:18:51",
              "date_uploaded_unix": 1542007131
            },
            {
              "url": "https://yts.mx/torrent/download/5ACEB9A75BD576A15EDA44E196E6569F052AA28D",
              "hash": "5ACEB9A75BD576A15EDA44E196E6569F052AA28D",
              "quality": "1080p",
              "type": "web",
              "seeds": 20,
              "peers": 4,
              "size": "2.64 GB",
              "size_bytes": 2834678415,
              "date_uploaded": "2018-11-12 10:38:01",
              "date_uploaded_unix": 1542015481
            }
          ],
          "date_uploaded": "2018-11-12 08:18:51",
          "date_uploaded_unix": 1542007131
        },
        {
          "id": 21870,
          "url": "https://yts.mx/movies/david-attenborough-a-life-on-our-planet-2020",
          "imdb_code": "tt11989890",
          "title": "David Attenborough: A Life on Our Planet",
          "title_english": "David Attenborough: A Life on Our Planet",
          "title_long": "David Attenborough: A Life on Our Planet (2020)",
          "slug": "david-attenborough-a-life-on-our-planet-2020",
          "year": 2020,
          "rating": 9,
          "runtime": 83,
          "genres": [
            "Action",
            "Biography",
            "Documentary"
          ],
          "summary": "One man has seen more of the natural world than any other. This unique feature documentary is his witness statement. In his 93 years, David Attenborough has visited every continent on the globe, exploring the wild places of our planet and documenting the living world in all its variety and wonder. Now, for the first time he reflects upon both the defining moments of his lifetime as a naturalist and the devastating changes he has seen. Honest, revealing and urgent, DAVID ATTENBOROUGH: A LIFE ON OUR PLANET is a powerful first-hand account of humanity's impact on nature and a message of hope for future generations. Created by award-winning natural history filmmakers Silverback Films and global conservation organization WWF, the film is Directed by Alastair Fothergill, Jonnie Hughes and Keith Scholey and Executive Produced by Colin Butfield. Celebrated British naturalist Sir David Attenborough has a broadcasting career spanning over eight decades. He has visited every continent on the ...",
          "description_full": "One man has seen more of the natural world than any other. This unique feature documentary is his witness statement. In his 93 years, David Attenborough has visited every continent on the globe, exploring the wild places of our planet and documenting the living world in all its variety and wonder. Now, for the first time he reflects upon both the defining moments of his lifetime as a naturalist and the devastating changes he has seen. Honest, revealing and urgent, DAVID ATTENBOROUGH: A LIFE ON OUR PLANET is a powerful first-hand account of humanity's impact on nature and a message of hope for future generations. Created by award-winning natural history filmmakers Silverback Films and global conservation organization WWF, the film is Directed by Alastair Fothergill, Jonnie Hughes and Keith Scholey and Executive Produced by Colin Butfield. Celebrated British naturalist Sir David Attenborough has a broadcasting career spanning over eight decades. He has visited every continent on the ...",
          "synopsis": "One man has seen more of the natural world than any other. This unique feature documentary is his witness statement. In his 93 years, David Attenborough has visited every continent on the globe, exploring the wild places of our planet and documenting the living world in all its variety and wonder. Now, for the first time he reflects upon both the defining moments of his lifetime as a naturalist and the devastating changes he has seen. Honest, revealing and urgent, DAVID ATTENBOROUGH: A LIFE ON OUR PLANET is a powerful first-hand account of humanity's impact on nature and a message of hope for future generations. Created by award-winning natural history filmmakers Silverback Films and global conservation organization WWF, the film is Directed by Alastair Fothergill, Jonnie Hughes and Keith Scholey and Executive Produced by Colin Butfield. Celebrated British naturalist Sir David Attenborough has a broadcasting career spanning over eight decades. He has visited every continent on the ...",
          "yt_trailer_code": "sbUNXyOQr40",
          "language": "en",
          "mpa_rating": "PG",
          "background_image": "https://yts.mx/assets/images/movies/david_attenborough_a_life_on_our_planet_2020/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/david_attenborough_a_life_on_our_planet_2020/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/david_attenborough_a_life_on_our_planet_2020/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/david_attenborough_a_life_on_our_planet_2020/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/david_attenborough_a_life_on_our_planet_2020/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/1BCE2AE49812E11591EFB8AA0314A6C0FEC209E7",
              "hash": "1BCE2AE49812E11591EFB8AA0314A6C0FEC209E7",
              "quality": "720p",
              "type": "web",
              "seeds": 55,
              "peers": 10,
              "size": "770.33 MB",
              "size_bytes": 807749550,
              "date_uploaded": "2020-10-04 16:57:50",
              "date_uploaded_unix": 1601823470
            },
            {
              "url": "https://yts.mx/torrent/download/CD2A82EDF1131C948E29D08E03C4BD1B6E6F38F3",
              "hash": "CD2A82EDF1131C948E29D08E03C4BD1B6E6F38F3",
              "quality": "1080p",
              "type": "web",
              "seeds": 186,
              "peers": 31,
              "size": "1.55 GB",
              "size_bytes": 1664299827,
              "date_uploaded": "2020-10-04 19:04:12",
              "date_uploaded_unix": 1601831052
            },
            {
              "url": "https://yts.mx/torrent/download/97907C67FCB48F9964C4DCB9C1715E9CE2D9AE17",
              "hash": "97907C67FCB48F9964C4DCB9C1715E9CE2D9AE17",
              "quality": "2160p",
              "type": "web",
              "seeds": 51,
              "peers": 3,
              "size": "3.7 GB",
              "size_bytes": 3972844749,
              "date_uploaded": "2020-10-10 14:14:54",
              "date_uploaded_unix": 1602332094
            }
          ],
          "date_uploaded": "2020-10-04 16:57:50",
          "date_uploaded_unix": 1601823470
        },
        {
          "id": 23876,
          "url": "https://yts.mx/movies/serendip-2018",
          "imdb_code": "tt8387538",
          "title": "Serendip",
          "title_english": "Serendip",
          "title_long": "Serendip (2018)",
          "slug": "serendip-2018",
          "year": 2018,
          "rating": 9,
          "runtime": 70,
          "genres": [
            "Documentary"
          ],
          "summary": "After months of pooling resources, Andrea finally joins Antonio in Sri Lanka, where he is already working to organize the delivery of school supplies for the children of Ambewela. After the successful initial phase, Take Me Back guys come into contact with voices, faces and ideas until they become witnesses of stories and live spectators of a faraway place, a place that screams diversity, change and possibility. What the two friends couldn't predict was how much the journey itself would become their path, allowing them to bring back home more than the feeling of having done something great.",
          "description_full": "After months of pooling resources, Andrea finally joins Antonio in Sri Lanka, where he is already working to organize the delivery of school supplies for the children of Ambewela. After the successful initial phase, Take Me Back guys come into contact with voices, faces and ideas until they become witnesses of stories and live spectators of a faraway place, a place that screams diversity, change and possibility. What the two friends couldn't predict was how much the journey itself would become their path, allowing them to bring back home more than the feeling of having done something great.",
          "synopsis": "After months of pooling resources, Andrea finally joins Antonio in Sri Lanka, where he is already working to organize the delivery of school supplies for the children of Ambewela. After the successful initial phase, Take Me Back guys come into contact with voices, faces and ideas until they become witnesses of stories and live spectators of a faraway place, a place that screams diversity, change and possibility. What the two friends couldn't predict was how much the journey itself would become their path, allowing them to bring back home more than the feeling of having done something great.",
          "yt_trailer_code": "",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/serendip_2018/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/serendip_2018/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/serendip_2018/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/serendip_2018/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/serendip_2018/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/D3BDFB38FDB2A90027CF20EE46257A930ADEF43F",
              "hash": "D3BDFB38FDB2A90027CF20EE46257A930ADEF43F",
              "quality": "720p",
              "type": "web",
              "seeds": 5,
              "peers": 1,
              "size": "641.87 MB",
              "size_bytes": 673049477,
              "date_uploaded": "2020-11-21 19:30:17",
              "date_uploaded_unix": 1605983417
            },
            {
              "url": "https://yts.mx/torrent/download/2C3E7F1637648C54BEB8947503D35F6BD20E2239",
              "hash": "2C3E7F1637648C54BEB8947503D35F6BD20E2239",
              "quality": "1080p",
              "type": "web",
              "seeds": 11,
              "peers": 3,
              "size": "1.29 GB",
              "size_bytes": 1385126953,
              "date_uploaded": "2020-11-21 21:12:16",
              "date_uploaded_unix": 1605989536
            }
          ],
          "date_uploaded": "2020-11-21 19:30:17",
          "date_uploaded_unix": 1605983417
        },
        {
          "id": 28964,
          "url": "https://yts.mx/movies/escape-from-room-18-2017",
          "imdb_code": "tt4688142",
          "title": "Escape from Room 18",
          "title_english": "Escape from Room 18",
          "title_long": "Escape from Room 18 (2017)",
          "slug": "escape-from-room-18-2017",
          "year": 2017,
          "rating": 9,
          "runtime": 60,
          "genres": [
            "Documentary"
          ],
          "summary": "John Daly, an ex-Neo Nazi, fled to Israel when his gang tried to kill him for being Jewish. An old Skinhead friend finds John 25 years later and suggests they visit concentration camps in an effort to make amends for their past.",
          "description_full": "John Daly, an ex-Neo Nazi, fled to Israel when his gang tried to kill him for being Jewish. An old Skinhead friend finds John 25 years later and suggests they visit concentration camps in an effort to make amends for their past.",
          "synopsis": "John Daly, an ex-Neo Nazi, fled to Israel when his gang tried to kill him for being Jewish. An old Skinhead friend finds John 25 years later and suggests they visit concentration camps in an effort to make amends for their past.",
          "yt_trailer_code": "",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/escape_from_room_18_2017/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/escape_from_room_18_2017/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/escape_from_room_18_2017/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/escape_from_room_18_2017/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/escape_from_room_18_2017/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/0E8EBCE2FCDA77C3BDC1DBBEFE020CE5725A02CF",
              "hash": "0E8EBCE2FCDA77C3BDC1DBBEFE020CE5725A02CF",
              "quality": "720p",
              "type": "web",
              "seeds": 31,
              "peers": 12,
              "size": "549.68 MB",
              "size_bytes": 576381256,
              "date_uploaded": "2021-03-17 01:14:15",
              "date_uploaded_unix": 1615940055
            },
            {
              "url": "https://yts.mx/torrent/download/BC9BC71B8958072CCA66723F23F92BA5FBBCF8BC",
              "hash": "BC9BC71B8958072CCA66723F23F92BA5FBBCF8BC",
              "quality": "1080p",
              "type": "web",
              "seeds": 38,
              "peers": 17,
              "size": "1020.34 MB",
              "size_bytes": 1069904036,
              "date_uploaded": "2021-03-17 01:55:06",
              "date_uploaded_unix": 1615942506
            }
          ],
          "date_uploaded": "2021-03-17 01:14:15",
          "date_uploaded_unix": 1615940055
        },
        {
          "id": 2429,
          "url": "https://yts.mx/movies/pulp-fiction-1994",
          "imdb_code": "tt0110912",
          "title": "Pulp Fiction",
          "title_english": "Pulp Fiction",
          "title_long": "Pulp Fiction (1994)",
          "slug": "pulp-fiction-1994",
          "year": 1994,
          "rating": 8.9,
          "runtime": 154,
          "genres": [
            "Action",
            "Crime",
            "Drama"
          ],
          "summary": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
          "description_full": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
          "synopsis": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
          "yt_trailer_code": "tGpTpVyI_OQ",
          "language": "en",
          "mpa_rating": "R",
          "background_image": "https://yts.mx/assets/images/movies/Pulp_Fiction_1994/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/Pulp_Fiction_1994/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/Pulp_Fiction_1994/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/Pulp_Fiction_1994/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/Pulp_Fiction_1994/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/D55F1E840F1BD6576EAD67A4D04E5D6EA294414B",
              "hash": "D55F1E840F1BD6576EAD67A4D04E5D6EA294414B",
              "quality": "720p",
              "type": "bluray",
              "seeds": 80,
              "peers": 5,
              "size": "751.29 MB",
              "size_bytes": 787784663,
              "date_uploaded": "2015-11-01 01:52:11",
              "date_uploaded_unix": 1446339131
            },
            {
              "url": "https://yts.mx/torrent/download/3F8F219568B8B229581DDDD7BC5A5E889E906A9B",
              "hash": "3F8F219568B8B229581DDDD7BC5A5E889E906A9B",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 188,
              "peers": 16,
              "size": "1.40 GB",
              "size_bytes": 1503238554,
              "date_uploaded": "2015-11-01 01:52:15",
              "date_uploaded_unix": 1446339135
            }
          ],
          "date_uploaded": "2015-11-01 01:52:11",
          "date_uploaded_unix": 1446339131
        },
        {
          "id": 2640,
          "url": "https://yts.mx/movies/schindlers-list-1993",
          "imdb_code": "tt0108052",
          "title": "Schindler's List",
          "title_english": "Schindler's List",
          "title_long": "Schindler's List (1993)",
          "slug": "schindlers-list-1993",
          "year": 1993,
          "rating": 8.9,
          "runtime": 195,
          "genres": [
            "Action",
            "Biography",
            "Drama",
            "History"
          ],
          "summary": "Oskar Schindler is a vain and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.",
          "description_full": "Oskar Schindler is a vain and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.",
          "synopsis": "Oskar Schindler is a vain and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.",
          "yt_trailer_code": "bJcLRFWxRno",
          "language": "en",
          "mpa_rating": "R",
          "background_image": "https://yts.mx/assets/images/movies/Schindlers_List_1993/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/Schindlers_List_1993/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/Schindlers_List_1993/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/Schindlers_List_1993/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/Schindlers_List_1993/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/69B6CF5AD84C75E257A0597F827E1F032BA831BF",
              "hash": "69B6CF5AD84C75E257A0597F827E1F032BA831BF",
              "quality": "720p",
              "type": "bluray",
              "seeds": 49,
              "peers": 14,
              "size": "1.20 GB",
              "size_bytes": 1288490189,
              "date_uploaded": "2015-11-01 01:16:11",
              "date_uploaded_unix": 1446336971
            },
            {
              "url": "https://yts.mx/torrent/download/F64C844C39FCD6A5F9157884E97296F7019DB83B",
              "hash": "F64C844C39FCD6A5F9157884E97296F7019DB83B",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 86,
              "peers": 19,
              "size": "2.50 GB",
              "size_bytes": 2684354560,
              "date_uploaded": "2015-11-01 01:16:14",
              "date_uploaded_unix": 1446336974
            }
          ],
          "date_uploaded": "2015-11-01 01:16:11",
          "date_uploaded_unix": 1446336971
        },
        {
          "id": 3489,
          "url": "https://yts.mx/movies/the-lord-of-the-rings-the-return-of-the-king-2003",
          "imdb_code": "tt0167260",
          "title": "The Lord of the Rings: The Return of the King",
          "title_english": "The Lord of the Rings: The Return of the King",
          "title_long": "The Lord of the Rings: The Return of the King (2003)",
          "slug": "the-lord-of-the-rings-the-return-of-the-king-2003",
          "year": 2003,
          "rating": 8.9,
          "runtime": 201,
          "genres": [
            "Action",
            "Adventure",
            "Drama",
            "Fantasy"
          ],
          "summary": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
          "description_full": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
          "synopsis": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
          "yt_trailer_code": "co9SNfJNDN8",
          "language": "en",
          "mpa_rating": "PG-13",
          "background_image": "https://yts.mx/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/FDF8D3EB9CD78DE60C3CBB3B68AF6C8A7D560E67",
              "hash": "FDF8D3EB9CD78DE60C3CBB3B68AF6C8A7D560E67",
              "quality": "720p",
              "type": "bluray",
              "seeds": 75,
              "peers": 28,
              "size": "1.70 GB",
              "size_bytes": 1825361101,
              "date_uploaded": "2015-11-01 02:58:16",
              "date_uploaded_unix": 1446343096
            },
            {
              "url": "https://yts.mx/torrent/download/AD73D5576DC4ECFEEA4353D4503F9B3F93DFA740",
              "hash": "AD73D5576DC4ECFEEA4353D4503F9B3F93DFA740",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 396,
              "peers": 98,
              "size": "3.70 GB",
              "size_bytes": 3972844749,
              "date_uploaded": "2015-11-01 02:58:18",
              "date_uploaded_unix": 1446343098
            }
          ],
          "date_uploaded": "2015-11-01 02:58:16",
          "date_uploaded_unix": 1446343096
        },
        {
          "id": 23103,
          "url": "https://yts.mx/movies/club-frontera-2016",
          "imdb_code": "tt3909186",
          "title": "Club Frontera",
          "title_english": "Club Frontera",
          "title_long": "Club Frontera (2016)",
          "slug": "club-frontera-2016",
          "year": 2016,
          "rating": 8.9,
          "runtime": 93,
          "genres": [
            "Documentary",
            "History",
            "Sport"
          ],
          "summary": "Club Frontera is a riveting documentary about the Club Tijuana Xoloitzcuintles (Xolos) professional Mexican soccer team and their positive impact on the city of Tijuana, Mexico. The compelling film follows players, fans, political figures, sports personalities, and enthusiasts from both sides of the border as they share their personal stories of how the newly emerging success of the Xolos is changing Tijuana for the better. Tijuana, nestled just south of the U.S. border with a turbulent history of violence and corruption, has long struggled to develop a collective identity. But with the emergence of the Xolos and their 2012 Championship season in Mexico's Premier League (Liga MX), Tijuanese may have finally found a rallying point to unify and rejuvenate the city into a 21st century cultural resurgence.",
          "description_full": "Club Frontera is a riveting documentary about the Club Tijuana Xoloitzcuintles (Xolos) professional Mexican soccer team and their positive impact on the city of Tijuana, Mexico. The compelling film follows players, fans, political figures, sports personalities, and enthusiasts from both sides of the border as they share their personal stories of how the newly emerging success of the Xolos is changing Tijuana for the better. Tijuana, nestled just south of the U.S. border with a turbulent history of violence and corruption, has long struggled to develop a collective identity. But with the emergence of the Xolos and their 2012 Championship season in Mexico's Premier League (Liga MX), Tijuanese may have finally found a rallying point to unify and rejuvenate the city into a 21st century cultural resurgence.",
          "synopsis": "Club Frontera is a riveting documentary about the Club Tijuana Xoloitzcuintles (Xolos) professional Mexican soccer team and their positive impact on the city of Tijuana, Mexico. The compelling film follows players, fans, political figures, sports personalities, and enthusiasts from both sides of the border as they share their personal stories of how the newly emerging success of the Xolos is changing Tijuana for the better. Tijuana, nestled just south of the U.S. border with a turbulent history of violence and corruption, has long struggled to develop a collective identity. But with the emergence of the Xolos and their 2012 Championship season in Mexico's Premier League (Liga MX), Tijuanese may have finally found a rallying point to unify and rejuvenate the city into a 21st century cultural resurgence.",
          "yt_trailer_code": "",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/club_frontera_2016/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/club_frontera_2016/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/club_frontera_2016/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/club_frontera_2016/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/club_frontera_2016/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/3D3CC033E65B836D6EB17248C37395CEF5B76DCB",
              "hash": "3D3CC033E65B836D6EB17248C37395CEF5B76DCB",
              "quality": "720p",
              "type": "web",
              "seeds": 0,
              "peers": 1,
              "size": "852.74 MB",
              "size_bytes": 894162698,
              "date_uploaded": "2020-11-03 13:30:44",
              "date_uploaded_unix": 1604406644
            },
            {
              "url": "https://yts.mx/torrent/download/419B19F0D5DEBBCD8CC37B3323FEBFD35100801B",
              "hash": "419B19F0D5DEBBCD8CC37B3323FEBFD35100801B",
              "quality": "1080p",
              "type": "web",
              "seeds": 0,
              "peers": 1,
              "size": "1.71 GB",
              "size_bytes": 1836098519,
              "date_uploaded": "2020-11-03 15:41:59",
              "date_uploaded_unix": 1604414519
            }
          ],
          "date_uploaded": "2020-11-03 13:30:44",
          "date_uploaded_unix": 1604406644
        },
        {
          "id": 26346,
          "url": "https://yts.mx/movies/fiddlin-2018",
          "imdb_code": "tt5618318",
          "title": "Fiddlin'",
          "title_english": "Fiddlin'",
          "title_long": "Fiddlin' (2018)",
          "slug": "fiddlin-2018",
          "year": 2018,
          "rating": 8.9,
          "runtime": 92,
          "genres": [
            "Documentary",
            "Music"
          ],
          "summary": "Fiddlin' is a foot-stomping celebration of true Americana and artistic expression. This hopeful, inspiring Old-Time/ Bluegrass music documentary shines a light on what is best about America. Filmed in the Appalachian Mountains at the World's Oldest Fiddler's Convention, Fiddlin' shows the uplifting and healing power of music. With multi-generations jamming together and kids holding instruments instead of phones, it feels like taking a step back in time as we witness some off-the-charts pickin' and fiddlin'.",
          "description_full": "Fiddlin' is a foot-stomping celebration of true Americana and artistic expression. This hopeful, inspiring Old-Time/ Bluegrass music documentary shines a light on what is best about America. Filmed in the Appalachian Mountains at the World's Oldest Fiddler's Convention, Fiddlin' shows the uplifting and healing power of music. With multi-generations jamming together and kids holding instruments instead of phones, it feels like taking a step back in time as we witness some off-the-charts pickin' and fiddlin'.",
          "synopsis": "Fiddlin' is a foot-stomping celebration of true Americana and artistic expression. This hopeful, inspiring Old-Time/ Bluegrass music documentary shines a light on what is best about America. Filmed in the Appalachian Mountains at the World's Oldest Fiddler's Convention, Fiddlin' shows the uplifting and healing power of music. With multi-generations jamming together and kids holding instruments instead of phones, it feels like taking a step back in time as we witness some off-the-charts pickin' and fiddlin'.",
          "yt_trailer_code": "RB25Y7zI_0w",
          "language": "en",
          "mpa_rating": "",
          "background_image": "https://yts.mx/assets/images/movies/fiddlin_2018/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/fiddlin_2018/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/fiddlin_2018/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/fiddlin_2018/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/fiddlin_2018/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/3792E4DCE29CACB3DD5D5C864F4E6C3ED6A71780",
              "hash": "3792E4DCE29CACB3DD5D5C864F4E6C3ED6A71780",
              "quality": "720p",
              "type": "web",
              "seeds": 5,
              "peers": 1,
              "size": "847.82 MB",
              "size_bytes": 889003704,
              "date_uploaded": "2021-01-23 08:26:35",
              "date_uploaded_unix": 1611386795
            },
            {
              "url": "https://yts.mx/torrent/download/A6FAD19D19241886FFC79369875C5927788C58B3",
              "hash": "A6FAD19D19241886FFC79369875C5927788C58B3",
              "quality": "1080p",
              "type": "web",
              "seeds": 4,
              "peers": 2,
              "size": "1.54 GB",
              "size_bytes": 1653562409,
              "date_uploaded": "2021-01-23 10:46:47",
              "date_uploaded_unix": 1611395207
            }
          ],
          "date_uploaded": "2021-01-23 08:26:35",
          "date_uploaded_unix": 1611386795
        },
        {
          "id": 1151,
          "url": "https://yts.mx/movies/fight-club-1999",
          "imdb_code": "tt0137523",
          "title": "Fight Club",
          "title_english": "Fight Club",
          "title_long": "Fight Club (1999)",
          "slug": "fight-club-1999",
          "year": 1999,
          "rating": 8.8,
          "runtime": 139,
          "genres": [
            "Action",
            "Drama"
          ],
          "summary": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.",
          "description_full": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.",
          "synopsis": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.",
          "yt_trailer_code": "BdJKm16Co6M",
          "language": "en",
          "mpa_rating": "R",
          "background_image": "https://yts.mx/assets/images/movies/Fight_Club_1999/background.jpg",
          "background_image_original": "https://yts.mx/assets/images/movies/Fight_Club_1999/background.jpg",
          "small_cover_image": "https://yts.mx/assets/images/movies/Fight_Club_1999/small-cover.jpg",
          "medium_cover_image": "https://yts.mx/assets/images/movies/Fight_Club_1999/medium-cover.jpg",
          "large_cover_image": "https://yts.mx/assets/images/movies/Fight_Club_1999/large-cover.jpg",
          "state": "ok",
          "torrents": [
            {
              "url": "https://yts.mx/torrent/download/4B37249E7F82F60D94C7A15B743A6B624E640372",
              "hash": "4B37249E7F82F60D94C7A15B743A6B624E640372",
              "quality": "720p",
              "type": "bluray",
              "seeds": 43,
              "peers": 4,
              "size": "1.00 GB",
              "size_bytes": 1073741824,
              "date_uploaded": "2015-10-31 23:25:31",
              "date_uploaded_unix": 1446330331
            },
            {
              "url": "https://yts.mx/torrent/download/A086CE4AFABBD8AB949662E30134A49E22D1F0C7",
              "hash": "A086CE4AFABBD8AB949662E30134A49E22D1F0C7",
              "quality": "1080p",
              "type": "bluray",
              "seeds": 276,
              "peers": 64,
              "size": "1.85 GB",
              "size_bytes": 1986422374,
              "date_uploaded": "2015-10-31 23:25:32",
              "date_uploaded_unix": 1446330332
            }
          ],
          "date_uploaded": "2015-10-31 23:25:31",
          "date_uploaded_unix": 1446330331
        }
      ]
    },
    "@meta": {
      "server_time": 1616142156,
      "server_timezone": "CET",
      "api_version": 2,
      "execution_time": "0.01 ms"
    }
  }